from flask import Flask
from flask_sqlalchemy import SQLAlchemy

#data model for user accounts
class User(db.Model):
    id = ...
    email = ...
    username = ...
    password = ...
    full_name = ...
    bio = ...
    contact_info = ...

class ItemListing(db.Model):
    id = ...
    name = ...
    seller = ...
    price = ...
    date_picked = ...
    location = ...
    description = ...

class OrdersPlaced(db.Model):
    id = ...
    name = ...
    seller = ...
    price = ...
    date_picked = ...
    date_placed = ...
    location = ...
    description = ...
    payment_method = ...

class OrdersSold(db.Model):
    id = ...
    name = ...
    buyer = ...
    price = ...
    date_picked = ...
    date_sold = ...
    location = ...
    description = ...
    payment_method = ...






