from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from app import db

#data model for user accounts
class User(db.Model):
    user_id = db.Column(db.Integer, primary_key = True)
    user_email = db.Column(db.String(100), unique = True, nullable = False)
    user_username = db.Column(db.String(64), unique = True, nullable = False)
    user_password = db.Column(db.String(50), unique = True, nullable = False)
    user_fullname = db.Column(db.String(50), unique = False, nullable = False)
    user_bio = db.Column(db.String(200), unique = False, nullable = False)
    user_phonenumber = db.Column(db.Integer(10), unique = True, nullable = False)

    

class ItemListing(db.Model):
    listing_id = db.Column(db.Integer, primary_key = User.id)
    name = ...
    seller = ...
    price = ...
    date_picked = ...
    location = ...
    description = ...

    user_id = db.Column(db.Integer, db.foreign_key("user.user_id"), nullable = False)

class OrdersPlaced(db.Model):
    id = ...
    name = ...
    seller = ...
    price = ...
    date_picked = ...
    date_placed = ...
    location = ...
    description = ...
    payment_method = ...

class OrdersSold(db.Model):
    id = ...
    name = ...
    buyer = ...
    price = ...
    date_picked = ...
    date_sold = ...
    location = ...
    description = ...
    payment_method = ...






